name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
    - name: Checkout jeometry
      uses: actions/checkout@v1
      with:
        ref: master
        repository: jeometry-org/jeometry
        path: jeometry
    - name: Build Jeometry
      run: mvn install --file ../jeometry/pom.xml
    - name: Checkout revolsys
      uses: actions/checkout@v1
      with:
        ref: master
        repository: revolsys/com.revolsys.open
        path: revolsys
    - name: Build Revolsys
      run: mvn install --file ../revolsys/pom.xml
